DataKingdomPy2/DataKingdomPy2/urls.py
# -*- coding:utf-8 -*-

"""DataKingdomPy2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from settings import MEDIA_ROOT
import xadmin

from users.views import LoginView, RegisterView, LogoutView
from competitions.views import AllCompetitionsView, CompetitionView, AttendedView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^ueditor/', include('DjangoUeditor.urls')),

    # 配置媒体文件
    # url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    url(r'^user/', include('users.urls', namespace="user")),

    url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^info/$', TemplateView.as_view(template_name="info.html"), name="info"),

    url(r'^competition/all-competitions/$', AllCompetitionsView.as_view(), name="all_competitions"),
    url(r'^competition/(?P<competition_id>\d+)/$', CompetitionView.as_view(), name="competition"),
    url(r'^competition/(?P<competition_id>\d+)/attend/$', AttendedView.as_view(), name="attend_competition"),
]

DataKingdomPy2/apps/users/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url

from .views import UserInfoView, UserAttendView, UserSetPasswordView
from .views import UserSetEmailView, UserUploadView, UserDownloadView

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name="info"),
    url(r'^set/email$', UserSetEmailView.as_view(), name="set_email"),
    url(r'^set/password$', UserSetPasswordView.as_view(), name="set_password"),
    url(r'^attend/$', UserAttendView.as_view(), name="attend"),

    url(r'^upload/$', UserUploadView.as_view(), name="upload"),
    url(r'^download/(?P<competition_id>\d+)/$', UserDownloadView.as_view(), name="download"),
]

DataKingdomPy2/apps/competitions/models.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from DjangoUeditor.models import UEditorField

from users.models import UserProfile


# 自定义上传方法
def upload_for_competition(instance, filename):
    return '/'.join(['competitions', instance.name, filename])


def upload_for_file(instance, filename):
    new_filename = instance.person.username + '.' + filename.split('.')[1]
    return '/'.join(['competitions', 'results', instance.competition.name, new_filename])


# 比赛信息模型
class Competition(models.Model):
    name = models.CharField(verbose_name=u"比赛名", max_length=50)
    is_team = models.BooleanField(verbose_name=u"是否组队参加", default=False)
    start_date = models.DateField(verbose_name=u"开始日期", null=True, blank=True)
    end_date = models.DateField(verbose_name=u"结束日期", null=True, blank=True)
    enroll_date = models.DateField(verbose_name=u"报名开始日期", null=True, blank=True)
    deadline = models.DateField(verbose_name=u"报名截止日期", null=True, blank=True)
    organization = models.CharField(verbose_name=u"学校(组织)", max_length=100, null=True, blank=True)
    image = models.ImageField(
        verbose_name=u"图片", max_length=100, upload_to=upload_for_competition, null=True, blank=True)
    exam = models.FileField(
        verbose_name=u"赛题", max_length=100, upload_to=upload_for_competition, null=True, blank=True)
    simple_intro = models.TextField(verbose_name=u"比赛简介", null=True, blank=True)
    detail = UEditorField(
        verbose_name=u"比赛详情", width=900, height=300, toolbars="full", imagePath="competitions/resources/",
        filePath="competitions/resources/", default='', blank=True)

    class Meta:
        verbose_name = u"比赛信息"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = Competition.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete(save=False)
        except Exception as e:
            pass
        super(Competition, self).save(*args, **kwargs)


# 参赛信息模型
class AttendedPerson(models.Model):
    competition = models.ForeignKey(Competition, verbose_name=u"参与赛事")
    person = models.ForeignKey(UserProfile, verbose_name=u"参赛者（队长）")
    file = models.FileField(verbose_name=u"提交结果", null=True, blank=True, upload_to=upload_for_file)

    class Meta:
        unique_together = ("competition", "person")
        verbose_name = u"参赛信息"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.competition.name + '-' + self.person.username

    def save(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = AttendedPerson.objects.get(id=self.id)
            if this.file != self.file:
                this.file.delete(save=False)
        except Exception as e:
            pass
        super(AttendedPerson, self).save(*args, **kwargs)

DataKingdomPy2/apps/competitions/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.http import HttpResponseRedirect

from .models import Competition, AttendedPerson
from utils.mixin_utils import LoginRequiredMixin


class AllCompetitionsView(View):
    def get(self, request):
        all_competitions = Competition.objects.all()
        return render(request, "all-competitions.html", {"all_competitions": all_competitions})


class CompetitionView(LoginRequiredMixin, View):
    def get(self, request, competition_id):
        is_attended = False
        competition = Competition.objects.get(id=competition_id)
        attended_person = AttendedPerson.objects.filter(person=request.user, competition=competition)
        if attended_person.count() > 0:
            is_attended = True
        return render(request, "competition.html", {"competition": competition, "is_attended": is_attended})


class AttendedView(LoginRequiredMixin, View):
    def post(self, request, competition_id):
        attended_person = AttendedPerson()
        competition = Competition.objects.get(id=competition_id)
        attended_person.person = request.user
        attended_person.competition = competition
        attended_person.save()
        return HttpResponseRedirect('/user/attend/')

DataKingdomPy2/templates/all-competitions.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>全部竞赛</title>
  <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
  <link rel="stylesheet" href="/static/css/dataKingdom.css">
</head>
<body class="cpt-page">
<nav class="navbar navbar-default page-nav" role="navigation">
  <a href="{% url 'index' %}"><ul class="nav navbar-nav nav-pills navbar-brand"><span class="brand">Data</span> Kingdom</ul></a>

  {% if not request.user.is_authenticated %}
  <ul class="nav navbar-nav nav-pills pull-right">
    <li><a href="{% url 'index' %}">主页</a></li>
    <li><a href="{% url 'all_competitions' %}">全部竞赛</a></li>
    <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
    <li><a href="{% url 'register' %}">注册</a></li>
  </ul>
  {% else %}
    <ul class="nav navbar-nav nav-pills pull-right">
    <li><a href="{% url 'index' %}">主页</a></li>
    <li><a href="{% url 'all_competitions' %}">全部竞赛</a></li>
    <li><a href="{% url 'user:info' %}"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></li>
    <li><a href="{% url 'logout' %}">注销</a></li>
    </ul>
  {% endif %}

</nav>

<div class="container-fluid all-page-header">
  <div class="row">
    <div class="col-md-4 col-md-offset-1 page-header-txt">
      <h1>竞赛列表</h1>
      <br>
      <div class="input-group">
        <input type="text" id="search" class="form-control" placeholder="搜索">
        <span id="search-btn" class="input-group-addon"><a><span class="glyphicon glyphicon-search"></span></a></span>
      </div>
    </div>
    <div class="col-md-4 pull-right">
      <img src="/static/img/colorful-cpt-img.png">
    </div>
  </div>
</div>

<div class="container competitions">
  {% for competition in all_competitions %}
  <div class="row competition-card">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="row">
          <div class="col-md-4 pull-left">
            <img src="{{ MEDIA_URL }}{{ competition.image }}">
          </div>
          <div class="col-md-7 cpt-txt">
            <h2>{{ competition.name }}</h2>
            <br>
            <p>{{ competition.simple_intro }}</p>
            <div class="foot row">
              <div class="col-md-10 pull-left">
                <p>报名时间：{{ competition.enroll_date }}~{{ competition.deadline }}</p>
              </div>
              <div class="col-md-2 pull-right">
                <a href="{% url 'competition' competition.id %}"><button type="button" class="btn btn-cpt">参加比赛</button></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

</div>

<div class="to-top img-circle hidden-xs">
  <span class="glyphicon glyphicon-upload"></span>
</div>

<footer>
  <div class="container text-center">
    <br>
    <h2>Data Kingdom</h2>
    <br>
    <br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <img class="QRcode" src="/static/img/QRcode.png">
      </div>
    </div>
    <br>
    <br>
    <br>
    <ul class="list-inline">
      <li><a href="{% url 'info' %}#info-about">关于数据王国</a></li>
      <li><a href="{% url 'info' %}#info-privacy">隐私协议</a></li>
      <li><a href="{% url 'info' %}#info-rules">服务规则</a></li>
      <li><a href="{% url 'info' %}#info-contact">联系我们</a></li>
    </ul>
  </div>
  <img class="footer-bg" src="/static/img/colorful-bottom.png">
</footer>

<script src="/static/jQuery/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<script src="/static/js/all-competitions.js"></script>
<script src="/static/js/all-page.js"></script>
</body>
</html>

DataKingdomPy2/templates/competition.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ competition.name }}</title>
  <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
  <link rel="stylesheet" href="/static/css/dataKingdom.css">
</head>
<body class="info-about-page">
<nav class="navbar navbar-default page-nav" role="navigation">
  <a href="{% url 'index' %}"><ul class="nav navbar-nav nav-pills navbar-brand"><span class="brand">Data</span> Kingdom</ul></a>

  {% if not request.user.is_authenticated %}
  <ul class="nav navbar-nav nav-pills pull-right">
    <li><a href="{% url 'index' %}">主页</a></li>
    <li><a href="{% url 'all_competitions' %}">全部竞赛</a></li>
    <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a></li>
    <li><a href="{% url 'register' %}">注册</a></li>
  </ul>
  {% else %}
    <ul class="nav navbar-nav nav-pills pull-right">
    <li><a href="{% url 'index' %}">主页</a></li>
    <li><a href="{% url 'all_competitions' %}">全部竞赛</a></li>
    <li><a href="{% url 'user:info' %}"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></li>
    <li><a href="{% url 'logout' %}">注销</a></li>
    </ul>
  {% endif %}
</nav>

<div class="container-fluid all-page-header">
  <div class="row">
    <div class="col-md-2 pull-right" style="padding-right: 0">
      <img src="/static/img/colorful-info-img.png">
    </div>
    <div class="col-md-6 col-md-offset-1 page-header-txt">
      <h1>{{ competition.name }}</h1>
      <br>
      <br>
      <a>
        {% if is_attended %}
          <button id="join" type="button" class="btn btn-default joined" disabled>已参赛</button>
        {% else %}
          <button id="join" type="button" class="btn btn-default">报名参赛</button>
        {% endif %}
      </a>
    </div>
  </div>
</div>

<div class="container-fluid content">
  <div class="row">
    <div class="col-md-3 col-md-offset-1 verticle-list">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="#info-intro">赛事介绍</a></li>
        <li><a href="#info-rules">比赛规则</a></li>
        <li><a href="#info-data">比赛数据</a></li>
        <li><a href="#info-FAQ">FAQ</a></li>
      </ul>
    </div>

    <div class="col-md-7 col-md-offset-4">
      <div class="pre-line content-txt">
        {% autoescape off %}
        {{ competition.detail }}
        {% endautoescape %}
      </div>
    </div>
  </div>
</div>

<div class="to-top img-circle hidden-xs">
  <span class="glyphicon glyphicon-upload"></span>
</div>

<div class="confirm">
    <div class="winBg"></div>
    <div class="container win">
        <div class="col-md-4 col-md-offset-4 panel panel-default win-panel text-center">
            <h2>你确定要参加比赛吗？</h2>
            <p>--------这里是小提示--------</p>
            <form method="post" action="{% url 'attend_competition' competition.id %}">
                <button id="OK" type="submit" class="btn btn-primary btn-lg">确定</button>
                <button id="cancel" type="button" class="btn btn-primary btn-lg">取消</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>

<footer>
  <div class="container text-center">
    <br>
    <h2>Data Kingdom</h2>
    <br>
    <br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <img class="QRcode" src="/static/img/QRcode.png">
      </div>
    </div>
    <br>
    <br>
    <br>
    <ul class="list-inline">
      <li><a href="{% url 'info' %}#info-about">关于数据王国</a></li>
      <li><a href="{% url 'info' %}#info-privacy">隐私协议</a></li>
      <li><a href="{% url 'info' %}#info-rules">服务规则</a></li>
      <li><a href="{% url 'info' %}#info-contact">联系我们</a></li>
    </ul>
  </div>
  <img class="footer-bg" src="/static/img/colorful-bottom.png">
</footer>
<script src="/static/jQuery/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<script src="/static/js/competition.js"></script>
<script>
    var listDiv = document.getElementsByClassName("verticle-list")[0];
    var icon = document.getElementsByClassName("to-top")[0];

    document.body.onscroll = function () {
        if (document.body.scrollTop !== 0)
            icon.style.display = "block";
        else
            icon.style.display = "none";


        if (document.body.scrollTop >= 400) {
            listDiv.style.position = "fixed";
            listDiv.style.top = "21px";
        } else {
            listDiv.style.position = "absolute"
            listDiv.style.top = "";
        }

    }

    icon.onclick = function () {
        document.body.scrollTop = 0;
    }
</script>
</body>
</html>

DataKingdomPy2/templates/user-attend.html
{% extends 'user-base.html' %}

{% block title %}{{ request.user.username }}-个人参赛{% endblock %}

{% block header %}
    <body class="profile-page profile-page-cpt">
{% endblock %}

{% block content %}
<div class="container-fluid content">
  <div class="row">
    <div class="col-md-2 col-md-offset-2 verticle-list">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'user:info' %}">个人信息</a></li>
        <li><a href="{% url 'user:set_email' %}">修改邮箱</a></li>
        <li><a href="{% url 'user:set_password' %}">修改密码</a></li>
        <li class="active"><a href="{% url 'user:attend' %}">参加比赛</a></li>
      </ul>
    </div>

    <div class="col-md-6 col-md-offset-4">
      {% if number > 0 %}
      <div class="container-fluid competitions">
        {% for competition in uploaded_competitions%}
        <div class="row competition-card">
          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="row">
                <div class="col-md-5 pull-left">
                  <img src="{{ MEDIA_URL }}{{ competition.competition.image }}">
                </div>
                <div class="col-md-7 cpt-txt">
                  <h2 onclick="window.location = {% url 'competition' competition.competition.id %}">{{ competition.competition.name }}</h2>
                  <div class="foot row">
                    <div class="col-md-2">
                      <a href="{% url 'user:download' competition.competition.id %}" target="_blank">
                        <button type="button" class="btn btn-cpt">下载试题</button>
                      </a>
                    </div>
                    <div class="col-md-2 col-md-offset-1">
                        <form class="cpt-form" method="post" enctype="multipart/form-data" action="{% url 'user:upload' %}">
                            <button type="submit" class="btn btn-cpt">修改数据</button>
                            <input type="file" name="file">
                            <input type="hidden" name="competition_id" value="{{ competition.competition.id }}">
                          {% csrf_token %}
                        </form>
                    </div>
                    <div>

                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% for competition in other_competitions%}
        <div class="row competition-card">
          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="row">
                <div class="col-md-5 pull-left">
                  <img src="{{ MEDIA_URL }}{{ competition.competition.image }}">
                </div>
                <div class="col-md-7 cpt-txt">
                  <h2 onclick="window.location = '{% url 'competition' competition.competition.id %}'">{{ competition.competition.name }}</h2>
                  <div class="foot row">
                    <div class="col-md-2">
                      <a href="{% url 'user:download' competition.competition.id %}" target="_blank">
                        <button type="button" class="btn btn-cpt">下载试题</button>
                      </a>
                    </div>
                    <div class="col-md-4 col-md-offset-1">
                        <form class="cpt-form" method="post" enctype="multipart/form-data" action="{% url 'user:upload' %}">
                            <button type="submit" class="btn btn-cpt">上传数据</button>
                            <input id="test" type="file" name="file">
                            <input type="hidden" name="competition_id" value="{{ competition.competition.id }}">
                          {% csrf_token %}
                        </form>
                    </div>
                    <p id="filePath"></p>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
      {% else %}
      <div class="content-txt">
        <h2>暂未参加任何比赛</h2>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

DataKingdomPy2/templates/user-info.html
{% extends 'user-base.html' %}

{% block title %}{{ request.user.username }}-个人信息{% endblock %}

{% block content %}
<div class="container-fluid content">
  <div class="row">
    <div class="col-md-2 col-md-offset-2 verticle-list">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="{% url 'user:info' %}">个人信息</a></li>
        <li><a href="{% url 'user:set_email' %}">修改邮箱</a></li>
        <li><a href="{% url 'user:set_password' %}">修改密码</a></li>
        <li><a href="{% url 'user:attend' %}">参加比赛</a></li>
      </ul>
    </div>

    <div class="col-md-6 col-md-offset-4">
      <div class="content-txt">
        <h2>个人信息</h2>
        <hr>
        <form method="post" action="{% url 'user:info' %}">
          <label>用户名:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
            <input type="text" class="form-control" value="{{ request.user.username }}" disabled>
          </div>

          <label>邮箱:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
            <input type="text" class="form-control" value="{{ request.user.email }}" disabled>
          </div>

          <label>性别:</label>
          <div class="gender-select">
            <label class="radio-inline"><input type="radio" name="gender" value="male" {% if request.user.gender == 'male' %}checked="checked"{% endif %}>男</label>
            <label class="radio-inline"><input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
          </div>

          <label>城市:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-home"></span></span>
            <input type="text" class="form-control" name="city" value="{{ request.user.city | default_if_none:''}}">
          </div>

          <label>身份证号:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
            <input type="text" class="form-control" name="identity" value="{{ request.user.identity | default_if_none:''}}">
          </div>

          <label>手机号码:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-phone"></span></span>
            <input type="text" class="form-control" name="mobile" value="{{ request.user.mobile | default_if_none:''}}">
          </div>

          <label>学校（组织）:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-education"></span></span>
            <input type="text" class="form-control" name="organization" value="{{ request.user.organization | default_if_none:''}}">
          </div>

          <label>入学年份:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            <input type="text" class="form-control" name="year" value="{{ request.user.year | default_if_none:''}}">
          </div>

          <label>专业（工作）:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-briefcase"></span></span>
            <input type="text" class="form-control" name="work" value="{{ request.user.work | default_if_none:''}}">
          </div>

          <label>个人介绍:</label>
          <textarea class="form-control" rows="4" name="introduction" placeholder="关于你。。。">{{ request.user.introduction | default_if_none:''}}</textarea>

          <button type="submit" class="btn btn-primary btn-lg">修改</button>
        {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

DataKingdomPy2/templates/user-set-email.html
{% extends 'user-base.html' %}

{% block title %}{{ request.user.username }}-账号设置{% endblock %}

{% block content %}
<div class="container-fluid content">
  <div class="row">
    <div class="col-md-2 col-md-offset-2 verticle-list">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'user:info' %}">个人信息</a></li>
        <li class="active"><a href="{% url 'user:set_email' %}">修改邮箱</a></li>
        <li><a href="{% url 'user:set_password' %}">修改密码</a></li>
        <li><a href="{% url 'user:attend' %}">参加比赛</a></li>
      </ul>
    </div>

    <div class="col-md-6 col-md-offset-4">
      <div class="content-txt">
        <h2>修改密码</h2>
        <hr>
        <form method="post" action="{% url 'user:set_email' %}">
          <label>请输入密码:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <input type="password" class="form-control" name="password">
          </div>

          {% if msg == "密码错误" %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <ul><li>密码错误</li></ul>
          </div>
          {% endif %}

          <label>新邮箱地址:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
            <input type="email" class="form-control" name="email">
          </div>

          {% if update_email_form.email.errors %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ update_email_form.email.errors }}
          </div>
          {% endif %}

          <button type="submit" class="btn btn-primary btn-lg">提交</button>
        {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

DataKingdomPy2/templates/user-set-password.html
{% extends 'user-base.html' %}

{% block title %}{{ request.user.username }}-账号设置{% endblock %}

{% block content %}
<div class="container-fluid content">
  <div class="row">
    <div class="col-md-2 col-md-offset-2 verticle-list">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url 'user:info' %}">个人信息</a></li>
        <li><a href="{% url 'user:set_email' %}">修改邮箱</a></li>
        <li class="active"><a href="{% url 'user:set_password' %}">修改密码</a></li>
        <li><a href="{% url 'user:attend' %}">参加比赛</a></li>
      </ul>
    </div>

    <div class="col-md-6 col-md-offset-4">
      <div class="content-txt">
        <h2>修改密码</h2>
        <hr>
        <form method="post" action="{% url 'user:set_password' %}">
          <label>旧密码:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <input type="password" class="form-control" name="old_password">
          </div>

          {% if message == "密码错误" %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <ul><li>密码错误</li></ul>
          </div>
          {% endif %}

          <label>新密码:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <input type="password" class="form-control" name="new_password_1">
          </div>

          {% if update_password_form.new_password_1.errors %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ update_password_form.new_password_1.errors }}
          </div>
          {% endif %}

          <label>确认密码:</label>
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <input type="password" class="form-control" name="new_password_2">
          </div>

          {% if message == "两次输入密码不相同" %}
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <ul><li>两次输入密码不相同</li></ul>
          </div>
          {% endif %}

          <button type="submit" class="btn btn-primary btn-lg">提交</button>
        {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}